import { useEffect, useState } from 'react';
import type { Assessment, Bootstrap, CallDetail, Detail, Reference, Segment, Task } from './types';
import { api, date, label } from './api';
import { Badge, Empty, Icon, Modal } from './ui';
import { EvidenceLink } from './catalog';

export function LeadDetail({ detail, bootstrap, emphasis, close, refresh, openCall, editLead, taskChange }: { detail: Detail; bootstrap: Bootstrap; emphasis: string; close: () => void; refresh: () => Promise<void>; openCall: (id: string, ref?: Reference) => void; editLead: () => void; taskChange: (task: Task, status: string, due?: string) => Promise<void> }) {
  const [section, setSection] = useState('assessment'); const [note, setNote] = useState(''); const [topic, setTopic] = useState('note');
  const [value, setValue] = useState('unknown'); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState('');
  const [historic, setHistoric] = useState<Assessment | null>(null); const [taskDates, setTaskDates] = useState<Record<string, string>>({});
  const [custom, setCustom] = useState<Record<string, string>>({});
  const assessment = (historic || detail.assessment)?.data;
  const topics = emphasis === 'pricing' ? ['objection','budget'] : emphasis === 'decision_process' ? ['authority','decision_process','procurement'] : emphasis === 'timing' ? ['timing','commitment'] : [];
  const claims = [...(assessment?.claims || [])].sort((a, b) => Number(topics.includes(b.topic)) - Number(topics.includes(a.topic)));
  async function submitNote() {
    setError('');
    try { await api(`/api/workspace/leads/${detail.lead.id}/notes`, 'POST', { text: note, topic, value, confirmed, generation: detail.head.generation }); setNote(''); await refresh(); }
    catch (e) { setError((e as Error).message); }
  }
  async function saveField(id: string, type: string) {
    try {
      const raw = custom[id] ?? ''; const value = raw === '' ? null : type === 'number' ? Number(raw) : type === 'boolean' ? raw === 'true' : raw;
      await api(`/api/workspace/leads/${detail.lead.id}/fields/${id}`, 'PUT', { version: detail.custom_values[id]?.version || 0, value });
      await refresh(); setCustom(previous => { const next = { ...previous }; delete next[id]; return next; });
    } catch (e) { setError((e as Error).message); }
  }
  return <Modal title={detail.lead.name} close={close} wide><div className="lead-detail">
    <div className="detail-identity"><span className="avatar large">{detail.lead.name.slice(0, 2).toUpperCase()}</span><div><h2>{detail.lead.company || 'Company unknown'}</h2><p>{detail.lead.phone} · {detail.lead.timezone}</p></div><button onClick={editLead}>Edit record</button></div>
    {detail.lead.sample && <p className="notice">Fictional sample lead. Excluded from real intelligence and sales metrics.</p>}
    <div className="detail-signals"><div><small>Potential</small><Badge value={assessment?.potential || 'unassessed'}/></div><div><small>Immediate priority</small><Badge value={detail.priority}/></div><div><small>Confidence / coverage</small><Badge value={assessment?.confidence || 'unknown'}/></div><div><small>Contact eligibility</small><Badge value={detail.eligibility}/></div></div>
    <p className="hint">{detail.priority_reason} Permission recorded is not permission to bypass calling preflight.</p>
    {detail.stale && <p className="notice warning">New source information or a human correction is waiting for reconciliation. The assessment below is the previous version, not the latest truth.</p>}
    {historic && <p className="notice warning">Viewing historical assessment #{historic.id}. <button onClick={() => setHistoric(null)}>Return to current assessment</button></p>}
    <nav className="detail-tabs" aria-label="Lead details">{[['assessment','Assessment'],['evidence','Full evidence'],['tasks','Commitments'],['calls','All calls'],['notes','Notes & corrections'],['fields','Custom fields']].map(([id, name]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}>{name}</button>)}</nav>
    {error && <p className="error" role="alert">{error}</p>}
    {section === 'assessment' && (assessment ? <section>
      <div className="section-heading"><h3>Why this assessment?</h3><Badge>Rubric v{assessment.rubric_version}</Badge></div>
      <div className="criteria-grid">{Object.entries(assessment.criteria).map(([name, criterion]) => <div key={name}><span>{label(name)}</span><strong>{label(criterion.value)}</strong><small>{label(criterion.source)}</small></div>)}</div>
      <p className="hint">{assessment.evidence_points} {assessment.points_label.toLowerCase()}. {assessment.coverage.processed_chunks}/{assessment.coverage.total_chunks} source chunks processed.</p>
      {!assessment.rubric_approved && <p className="notice">Rubric not approved. Commercial potential remains unassessed.</p>}
      {!!assessment.conflicts.length && <div className="notice warning"><h3>Conflicting information retained</h3>{assessment.conflicts.map((conflict, index) => <p key={index}><strong>{label(conflict.topic)}:</strong> {conflict.reason}</p>)}</div>}
      <h3>Important unknowns</h3><div className="unknowns">{assessment.unknowns.map((unknown, i) => <p key={i}><span>?</span>{unknown}</p>)}</div>
      <h3>Supported reasons</h3>{claims.slice(0, 5).map(claim => <article className="claim" key={claim.id}><span className="eyebrow">{label(claim.topic)} · {label(claim.interpretation)}</span><p>{claim.text}</p>{claim.references.map((ref, index) => <EvidenceLink key={index} reference={ref}/>)}</article>)}
      <p className="hint">Exact quotes establish provenance, not a guarantee that the model interpreted the conversation correctly. Human review remains available.</p>
      <div className="section-heading"><h3>Assessment history</h3><span>{detail.history.length} most recent versions</span></div>{detail.history.map(version => <button className="history-row" key={version.id} onClick={() => void api<Assessment>(`/api/workspace/assessments/${version.id}?lead_id=${detail.lead.id}`).then(setHistoric).catch(e => setError((e as Error).message))}><span>#{version.id} · {date(version.created_at, bootstrap.timezone)}</span><Badge value={version.potential}/></button>)}
    </section> : <Empty title="This lead is not assessed yet" text={`Analysis state: ${label(detail.head.status)}. Calls, notes, and all underlying records remain available.`}/>)}
    {section === 'evidence' && <section><h3>All claims and their captured sources</h3>{!claims.length && <Empty title="No supported claims yet" text="Inspect the call history or add a human note. There are no fabricated citations."/>}{claims.map(claim => <article className="claim" key={claim.id}><div className="section-heading"><span className="eyebrow">{label(claim.topic)}</span><Badge value={claim.interpretation}/></div><p>{claim.text}</p>{claim.references.map((ref, i) => <div className="source-quote" key={i}><blockquote>{ref.quote}</blockquote><EvidenceLink reference={ref}/><small>{ref.call_id ? `Call ${ref.call_id.slice(-8)} · source revision ${claim.source_revision}` : `Note ${ref.note_id?.slice(-8)}`}{ref.source_time == null ? ' · timing not supplied' : ` · source offset ${ref.source_time} ms`}</small></div>)}</article>)}</section>}
    {section === 'tasks' && <section><h3>Agreements, requests, and recommendations</h3><p className="notice">All tasks are internal records. Marking a task done does not execute a call, send a message, confirm a booking, or transfer anyone.</p>{!detail.tasks.length && <Empty title="No internal work recorded"/>}{detail.tasks.map(task => <article className="detail-task" key={task.id}><div className="section-heading"><Badge value={task.status}/><span>{label(task.party)} · {label(task.kind)}</span></div><p>{task.data.wording}</p><small>{label(task.data.nature)} · {label(task.data.date_resolution)}</small>{task.data.reference && <EvidenceLink reference={task.data.reference}/>}<p>{task.due_at ? date(task.due_at, bootstrap.timezone) : task.data.date_phrase || 'No agreed deadline'}</p>{task.data.source_active === false && <p className="error">Supporting evidence was revised or redacted. Review this commitment.</p>}<div className="task-controls"><label>Human-confirmed due time<input aria-label={`Due time for ${task.id}`} type="text" placeholder="2026-09-18T10:00:00+03:00" value={taskDates[task.id] || ''} onChange={e => setTaskDates({ ...taskDates, [task.id]: e.target.value })}/></label><label>Internal state<select aria-label={`State for ${task.id}`} value={task.status} onChange={e => void taskChange(task, e.target.value, taskDates[task.id] || undefined).catch(e => setError((e as Error).message))}>{['proposed','needs_review','open','waiting','done','cancelled'].map(status => <option key={status} value={status}>{label(status)}</option>)}</select></label><button onClick={() => void taskChange(task, task.status, taskDates[task.id] || undefined).catch(e => setError((e as Error).message))}>Save due time</button></div></article>)}</section>}
    {section === 'calls' && <section><h3>Linked calls</h3><p className="hint">Real and practice calls are separately labeled. Practice does not contribute to this lead’s real assessment.</p>{!detail.calls.length && <Empty title="This lead has not been called"/>}{detail.calls.map(call => <button className="call-history-row" key={call.call_id} onClick={() => openCall(call.call_id)}><span><strong>{call.kind === 'twilio' ? 'Phone call record' : 'Practice only'}</strong><small>{date(call.created_at, bootstrap.timezone)} · {call.segment_count} captured fragments</small></span><Badge value={call.status}/><Icon name="arrow"/></button>)}{detail.calls.length >= 50 && <p className="notice">Showing the 50 most recent linked calls. Use the paginated Calls API for older records.</p>}</section>}
    {section === 'notes' && <section><h3>Human notes & corrections</h3>{detail.notes.map(item => <article className={`human-note ${item.active ? '' : 'superseded'}`} key={item.id} id={item.id}><div className="tags"><Badge>{item.confirmed ? 'Human-confirmed correction' : 'Human note'}</Badge>{!item.active && <Badge>Superseded, retained</Badge>}</div><p>{item.text}</p><small>{label(item.topic)} · {label(item.value)} · {date(item.created_at, bootstrap.timezone)}</small></article>)}<form onSubmit={e => { e.preventDefault(); void submitNote(); }}><label>New note<textarea rows={4} required maxLength={5000} value={note} onChange={e => setNote(e.target.value)}/></label><div className="form-grid"><label>Topic<select value={topic} onChange={e => setTopic(e.target.value)}>{['note','need','fit','intent','authority','timing','objection'].map(name => <option key={name} value={name}>{label(name)}</option>)}</select></label><label>Criterion answer<select value={value} onChange={e => setValue(e.target.value)}>{['unknown','yes','no'].map(v => <option value={v} key={v}>{label(v)}</option>)}</select></label></div><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>This is a confirmed human correction, not an unreviewed inference</label><p className="hint">Confirmed corrections take precedence in reconciliation. New contradictory evidence remains visible as a conflict.</p><button className="primary">Save human note</button></form></section>}
    {section === 'fields' && <section><h3>Typed custom fields</h3>{!bootstrap.fields.length && <Empty title="No custom fields defined" text="Use Customize → Custom field to define fields. Definition and knowing a value are separate."/>}{bootstrap.fields.map(field => { const raw = custom[field.id] ?? String(detail.custom_values[field.id]?.value ?? ''); return <div className="field-value" key={field.id}><label>{field.name}<small>{label(field.type)} · {field.id}</small>{field.type === 'select' || field.type === 'boolean' ? <select value={raw} onChange={e => setCustom({ ...custom, [field.id]: e.target.value })}><option value="">Unknown</option>{(field.type === 'boolean' ? ['true','false'] : field.options).map(option => <option key={option} value={option}>{option}</option>)}</select> : <input type={field.type === 'date' ? 'date' : field.type === 'number' ? 'number' : 'text'} placeholder="Unknown" value={raw} onChange={e => setCustom({ ...custom, [field.id]: e.target.value })}/>}</label><button onClick={() => void saveField(field.id, field.type)}>Save value</button></div>; })}</section>}
    <footer className="detail-footer"><span>No outbound action is performed in this workspace.</span><a href="/?legacy=1#leads">Open existing calling controls ↗</a></footer>
  </div></Modal>;
}
export function CallViewer({ id, reference, zone, close }: { id: string; reference?: Reference; zone: string; close: () => void }) {
  const [data, setData] = useState<CallDetail | null>(null); const [error, setError] = useState(''); const [offset, setOffset] = useState(0); const [replaced, setReplaced] = useState(false);
  const [correction, setCorrection] = useState<Segment | null>(null); const [text, setText] = useState(''); const [reason, setReason] = useState('');
  useEffect(() => { const controller = new AbortController(); void api<CallDetail>(`/api/workspace/calls/${id}?offset=${offset}&include_replaced=${replaced}`, 'GET', undefined, controller.signal).then(setData).catch(e => { if (!controller.signal.aborted) setError((e as Error).message); }); return () => controller.abort(); }, [id, offset, replaced]);
  useEffect(() => { if (!data || !reference?.segment_id || !data.call.lead_id) return;
    const existing = document.getElementById(reference.segment_id); if (existing) { existing.scrollIntoView({ block: 'center' }); existing.focus({ preventScroll: true }); return; }
    const controller = new AbortController(); void api<Segment>(`/api/workspace/segments/${reference.segment_id}?lead_id=${data.call.lead_id}`, 'GET', undefined, controller.signal).then(segment => { if (!segment.active) setReplaced(true); setOffset(Math.max(0, segment.seq - 4)); }).catch(e => { if (!controller.signal.aborted) setError((e as Error).message); }); return () => controller.abort();
  }, [data, reference]);
  async function saveCorrection() { if (!data || !correction) return; try { await api(`/api/workspace/segments/${correction.id}/correct`, 'POST', { revision: data.capture.revision, text, reason }); setCorrection(null); setData(await api<CallDetail>(`/api/workspace/calls/${id}?offset=${offset}&include_replaced=${replaced}`)); } catch (e) { setError((e as Error).message); } }
  return <Modal title="Call evidence" close={close} wide><div className="call-detail">{error && <p className="error" role="alert">{error}</p>}{!data ? <div className="loading">Loading captured evidence…</div> : <>
    <div className="tags"><Badge value={data.call.status}/><Badge>{data.call.kind === 'twilio' ? 'Phone call record' : 'Practice / demo only'}</Badge><Badge value={data.capture.dropped ? 'review' : 'neutral'}>{label(data.capture.status)}</Badge></div>
    <h3>{data.call.summary || 'No per-call summary captured'}</h3><p>{data.call.next_step || 'No next step saved by the in-call backend.'}</p>
    <div className="notice">No audio recording is stored. A finished call or provider close event is not proof of a complete transcript. {data.capture.dropped > 0 && `${data.capture.dropped} source events could not be stored because the capture limit was reached.`}</div>
    <details><summary>Operational details & captured actions</summary><dl className="operational"><dt>Call ID</dt><dd>{data.call.id}</dd><dt>Provider ID</dt><dd>{data.call.provider_sid || 'Not provided'}</dd><dt>Session ID</dt><dd>{data.call.session_id || 'Not provided'}</dd><dt>Created</dt><dd>{date(data.call.created_at, zone)}</dd><dt>Ended</dt><dd>{date(data.call.ended_at, zone)}</dd><dt>Outcome</dt><dd>{label(data.call.outcome)}</dd><dt>Capture revision</dt><dd>{data.capture.revision}</dd><dt>Capture flags</dt><dd>{data.capture.flags.map(label).join('; ') || 'None reported; completeness still unverified'}</dd><dt>Provider usage finalized</dt><dd>{data.call.usage_finalized ? 'Yes' : 'No'}</dd><dt>Captured usage</dt><dd><pre>{data.call.usage ? JSON.stringify(data.call.usage, null, 2) : 'Not provided'}</pre></dd><dt>Error</dt><dd>{data.call.error || 'No error captured'}</dd></dl><h4>Requests — not bookings or transfers</h4>{data.call.requests.length ? data.call.requests.map((request, index) => <p key={index}><strong>{label(request.type)}</strong>: {request.details} <Badge value={request.status}/></p>) : <p className="muted">No requests saved.</p>}<h4>Tool/action results</h4>{data.tool_results.length ? data.tool_results.map((tool, index) => <details key={index}><summary>{tool.summary} · {date(tool.created_at, zone)}</summary><pre>{JSON.stringify(tool.data, null, 2)}</pre></details>) : <p className="muted">No tool results captured.</p>}</details>
    <div className="section-heading"><h3>Source transcript</h3><label className="check-label"><input type="checkbox" checked={replaced} onChange={e => { setReplaced(e.target.checked); setOffset(0); }}/>Include superseded fragments</label></div><p className="hint">Channel attribution comes from the source event type, not diarization. Timing is shown only when supplied. Fragments may overlap or represent interrupted speech.</p>
    {!data.segments.length && <Empty title="No usable transcript captured" text="The operational call record is preserved. No conversation or qualification has been invented."/>}
    <div className="transcript">{data.segments.map((segment, index, list) => <div className={`transcript-fragment ${segment.role} ${reference?.segment_id === segment.id ? 'source-highlight' : ''} ${!segment.active ? 'superseded' : ''}`} key={segment.id} id={segment.id} tabIndex={-1}>
      {(index === 0 || segment.role !== list[index - 1].role) && <div className="speaker">{segment.role === 'lead' ? 'Lead channel' : segment.role === 'agent' ? 'Agent channel' : 'Unknown speaker'}</div>}<span className="fragment-text">{segment.redacted ? '[Redacted by operator]' : segment.text}</span><span className="fragment-meta">#{segment.seq} · {segment.start_ms == null ? 'Timing not provided' : `${segment.start_ms}–${segment.end_ms ?? '?'} ms`}{!segment.active && ' · Superseded'} <button aria-label={`Correct source segment ${segment.seq}`} disabled={!segment.active || segment.redacted} onClick={() => { setCorrection(segment); setText(segment.text); setReason(''); }}>Correct</button></span></div>)}</div>
    <div className="pager"><span>{data.total_segments ? offset + 1 : 0}–{offset + data.segments.length} of {data.total_segments} fragments</span><div><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}>Earlier</button><button disabled={!data.has_more} onClick={() => setOffset(offset + data.segments.length)}>Later</button></div></div>
    {correction && <div className="correction-editor"><h3>Audited source correction</h3><p>The captured original remains available as a superseded segment. This invalidates stale analysis; it does not silently overwrite evidence.</p><label>Corrected text<textarea rows={4} value={text} onChange={e => setText(e.target.value)}/></label><label>Reason<input minLength={5} maxLength={500} value={reason} onChange={e => setReason(e.target.value)}/></label><div className="modal-actions"><button onClick={() => setCorrection(null)}>Cancel</button><button className="primary" disabled={reason.length < 5} onClick={() => void saveCorrection()}>Save source revision</button></div></div>}
  </>}</div></Modal>;
}
