import { useState } from 'react';
import type { Bootstrap, Column, FieldDefinition, Filter, Lead, Operation, Query, View, Widget, Kind, Rubric } from './types';
import { api, identifier, label } from './api';
import { Modal, Icon } from './ui';

export const columnNames = ['name','company','potential','priority','confidence','eligibility','stage','next_action','assessment_at'];
export const widgetKinds: Kind[] = ['PriorityQueue','LeadsTable','PipelineBoard','Commitments','CallTimeline','EvidencePanel','Questions','RecentChanges','Objections'];
export const widgetLabels: Record<Kind, string> = { PriorityQueue: 'Priority queue', LeadsTable: 'Leads table', PipelineBoard: 'Pipeline board', Commitments: 'Commitments & follow-ups', CallTimeline: 'Call timeline', EvidencePanel: 'Evidence & assessment', Questions: 'Unresolved questions', RecentChanges: 'Recent changes', Objections: 'Supported objections' };
const filters = ['potential','priority','eligibility','stage','company','name','needs_review','awaiting_proposal','procurement','needs_decision','has_tasks','due_today','unknowns','objection'];
const booleanFields = ['needs_review','awaiting_proposal','procurement','needs_decision','has_tasks','due_today'];
export function QueryControls({ query, onChange, fields = [] }: { query: Query; onChange: (query: Query) => void; fields?: FieldDefinition[] }) {
  function update(index: number, patch: Partial<Filter>) { onChange({ ...query, filters: query.filters.map((f, i) => i === index ? { ...f, ...patch } : f) }); }
  return <div className="query-controls"><div className="form-grid"><label>Sort by<select value={query.sort} onChange={e => onChange({ ...query, sort: e.target.value as Query['sort'] })}>{['priority','potential','name','company','stage','created_at','assessment_at'].map(f => <option key={f} value={f}>{label(f)}</option>)}</select></label><label>Direction<select value={query.direction} onChange={e => onChange({ ...query, direction: e.target.value as Query['direction'] })}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><label>Group by<select value={query.group} onChange={e => onChange({ ...query, group: e.target.value as Query['group'] })}>{['none','priority','potential','stage','eligibility','company'].map(f => <option key={f} value={f}>{label(f)}</option>)}</select></label><label>Dataset<select value={query.scope} onChange={e => onChange({ ...query, scope: e.target.value as Query['scope'] })}><option value="real">Real leads only</option><option value="practice">Fictional sample leads only</option></select></label></div>
    <div className="section-heading"><h3>Filters <small>All must match</small></h3><button type="button" disabled={query.filters.length >= 10} onClick={() => onChange({ ...query, filters: [...query.filters, { field: 'potential', op: 'eq', value: 'promising' }] })}><Icon name="plus" size={14}/>Add filter</button></div>
    {!query.filters.length && <p className="muted">No filters. This view includes every lead in its dataset.</p>}
    {query.filters.map((filter, index) => <div className="filter-line" key={index}><select aria-label={`Filter ${index + 1} field`} value={filter.field} onChange={e => update(index, { field: e.target.value, value: booleanFields.includes(e.target.value) ? true : '' })}>{[...filters, ...fields.map(f => f.id)].map(f => <option key={f} value={f}>{fields.find(field => field.id === f)?.name || label(f)}</option>)}</select><select aria-label={`Filter ${index + 1} operator`} value={filter.op} onChange={e => update(index, { op: e.target.value as Filter['op'], value: e.target.value === 'in' ? [] : e.target.value === 'unknown' ? null : '' })}>{['eq','contains','in','unknown'].map(o => <option key={o} value={o}>{o === 'eq' ? 'equals' : o === 'in' ? 'one of' : label(o)}</option>)}</select>{filter.op !== 'unknown' && (booleanFields.includes(filter.field) ? <select aria-label={`Filter ${index + 1} value`} value={String(filter.value)} onChange={e => update(index, { value: e.target.value === 'true' })}><option value="true">Yes</option><option value="false">No</option></select> : <input aria-label={`Filter ${index + 1} value`} value={Array.isArray(filter.value) ? filter.value.join(', ') : String(filter.value ?? '')} placeholder={filter.op === 'in' ? 'Comma-separated values' : 'Value'} onChange={e => update(index, { value: filter.op === 'in' ? e.target.value.split(',').map(v => v.trim()) : fields.find(f => f.id === filter.field)?.type === 'number' ? Number(e.target.value) : e.target.value })}/>)}<button type="button" aria-label={`Remove filter ${index + 1}`} onClick={() => onChange({ ...query, filters: query.filters.filter((_, i) => i !== index) })}><Icon name="close" size={14}/></button></div>)}
    <p className="hint">Stored values use underscores: permission_recorded, permission_missing, unassessed, needs_review. A saved query never creates records.</p>
  </div>;
}
export function ViewEditor({ view, bootstrap, duplicate = false, initialQuery, close, save }: { view: View; bootstrap: Bootstrap; duplicate?: boolean; initialQuery?: Query; close: () => void; save: (ops: Operation[], reason: string, newId?: string) => Promise<void> }) {
  const [name, setName] = useState(duplicate ? `${view.name} — custom` : view.name);
  const [query, setQuery] = useState(initialQuery || structuredClone(view.query));
  const [emphasis, setEmphasis] = useState(view.emphasis); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit() {
    setSaving(true); setError('');
    try { const id = duplicate ? identifier('view') : view.id;
      const op: Operation = duplicate ? { op: 'create_view', view_id: id, name, query, duplicate_from: view.id } : { op: 'edit_view', view_id: id, name, query, emphasis };
      await save([op], duplicate ? `Created view “${name}”` : `Updated view “${name}”`, duplicate ? id : undefined); close();
    } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  return <Modal title={duplicate ? 'Create a saved view' : 'Customize this view'} close={close} wide><form onSubmit={e => { e.preventDefault(); void submit(); }}>
    <label>View name<input required maxLength={100} value={name} onChange={e => setName(e.target.value)}/></label>
    <QueryControls query={query} onChange={setQuery} fields={bootstrap.fields}/>
    <label>Lead detail emphasis<select value={emphasis} onChange={e => setEmphasis(e.target.value as View['emphasis'])}>{['overview','pricing','decision_process','timing','conflicts'].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></label><p className="hint">This emphasizes relevant sections without hiding full evidence or call history.</p>
    {!duplicate && view.id === 'all' && <p className="notice">All leads stays unfiltered. Use “Create a saved view” to keep a filtered version.</p>}
    {error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save view'}</button></footer>
  </form></Modal>;
}
export function WidgetEditor({ widget, fields, close, save }: { widget: Widget; fields: FieldDefinition[]; close: () => void; save: (widget: Widget) => Promise<void> }) {
  const [value, setValue] = useState(structuredClone(widget)); const [error, setError] = useState('');
  function column(index: number, patch: Partial<Column>) { setValue({ ...value, columns: value.columns.map((c, i) => i === index ? { ...c, ...patch } : c) }); }
  function move(index: number, delta: number) { const columns = [...value.columns]; [columns[index], columns[index + delta]] = [columns[index + delta], columns[index]]; setValue({ ...value, columns }); }
  return <Modal title="Configure widget" close={close} wide><form onSubmit={e => { e.preventDefault(); void save(value).then(close).catch(e => setError((e as Error).message)); }}><div className="form-grid"><label>Title<input required maxLength={100} value={value.title} onChange={e => setValue({ ...value, title: e.target.value })}/></label><label>Visible item limit<input type="number" min={5} max={50} value={value.limit} onChange={e => setValue({ ...value, limit: Number(e.target.value) })}/></label></div>
    <p className="hint">Data binding: {label(value.binding)}. Records and totals come from the server, not this configuration.</p>
    {widget.kind === 'LeadsTable' && <><h3>Table columns</h3>{value.columns.map((c, index) => <div className="column-editor" key={c.field}><label className="check-label"><input type="checkbox" checked={c.visible} onChange={e => column(index, { visible: e.target.checked })}/>{fields.find(f => f.id === c.field)?.name || label(c.field)}</label><label>Width<input aria-label={`${c.field} column width`} type="number" min={80} max={500} value={c.width} onChange={e => column(index, { width: Number(e.target.value) })}/></label><button type="button" aria-label={`Move ${c.field} left`} disabled={index === 0} onClick={() => move(index, -1)}>←</button><button type="button" aria-label={`Move ${c.field} right`} disabled={index === value.columns.length - 1} onClick={() => move(index, 1)}>→</button></div>)}
    <label>Add a column<select value="" onChange={e => { if (e.target.value) setValue({ ...value, columns: [...value.columns, { field: e.target.value, width: 160, visible: true }] }); }}><option value="">Choose a column</option>{[...columnNames, ...fields.map(f => f.id)].filter(f => !value.columns.some(c => c.field === f)).map(f => <option value={f} key={f}>{fields.find(field => field.id === f)?.name || label(f)}</option>)}</select></label></>}
    {error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save widget</button></footer></form></Modal>;
}
export function AddWidget({ close, save }: { close: () => void; save: (kind: Kind) => Promise<void> }) {
  const [error, setError] = useState('');
  return <Modal title="Add a workspace widget" close={close}><p>Every widget has a working server data path. Nothing here creates fictional pipeline activity.</p><div className="widget-picker">{widgetKinds.map(kind => <button key={kind} onClick={() => void save(kind).then(close).catch(e => setError((e as Error).message))}><Icon name={kind === 'CallTimeline' ? 'phone' : kind === 'EvidencePanel' ? 'link' : 'grid'}/><span>{widgetLabels[kind]}</span><Icon name="plus" size={16}/></button>)}</div>{error && <p className="error" role="alert">{error}</p>}</Modal>;
}
export function LeadEditor({ lead, close, saved }: { lead?: Lead; close: () => void; saved: (id: string) => Promise<void> }) {
  const [value, setValue] = useState({ name: lead?.name || '', company: lead?.company || '', phone: lead?.phone || '', timezone: lead?.timezone || 'Africa/Cairo', language: lead?.language || 'English', notes: lead?.notes || '', consent: lead?.consent || false, consent_note: lead?.consent_note || '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit() { setSaving(true); setError(''); try { const result = await api<{ lead?: Lead; id?: string }>(lead ? `/api/leads/${lead.id}` : '/api/leads', lead ? 'PUT' : 'POST', value); await saved(lead?.id || result.lead?.id || result.id || ''); close(); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  return <Modal title={lead ? 'Edit lead record' : 'Add a lead'} close={close}><form onSubmit={e => { e.preventDefault(); void submit(); }}><div className="form-grid">{(['name','company','phone','timezone','language'] as const).map(field => <label key={field}>{label(field)}<input required={['name','phone','timezone'].includes(field)} readOnly={field === 'phone' && !!lead} value={value[field]} onChange={e => setValue({ ...value, [field]: e.target.value })} placeholder={field === 'phone' ? '+ country code and number' : undefined}/></label>)}</div><label>Human notes<textarea rows={4} maxLength={5000} value={value.notes} onChange={e => setValue({ ...value, notes: e.target.value })}/></label><label className="check-label"><input type="checkbox" checked={value.consent} disabled={lead?.opted_out} onChange={e => setValue({ ...value, consent: e.target.checked })}/>I have recorded permission and supporting evidence for this contact</label><label>Permission evidence<textarea rows={3} maxLength={1000} value={value.consent_note} onChange={e => setValue({ ...value, consent_note: e.target.value })}/></label><p className="notice">Saving a contact never places a call. Permanent suppression cannot be removed here. Existing calling gates still apply.</p>{error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save lead'}</button></footer></form></Modal>;
}
export function ImportEditor({ close, saved }: { close: () => void; saved: () => Promise<void> }) {
  const [csv, setCsv] = useState(''); const [error, setError] = useState(''); const [result, setResult] = useState<{ added: number; duplicates: number; errors: { row: number; error: string }[] } | null>(null);
  return <Modal title="Import contacts from CSV" close={close} wide><form onSubmit={e => { e.preventDefault(); void api<typeof result>('/api/leads/import', 'POST', { csv }).then(async value => { setResult(value); await saved(); }).catch(e => setError((e as Error).message)); }}><p>Required columns: name, phone. Optional: company, timezone, language, notes, consent, consent_note. Up to 1,000 rows per import.</p><label>CSV contents<textarea rows={10} value={csv} onChange={e => setCsv(e.target.value)} placeholder="name,phone,company,timezone,consent,consent_note" required/></label><p className="hint">Importing never starts calls. Missing permission stays missing. Duplicate telephone identities keep the original record.</p>{result && <div className="notice"><strong>{result.added} added · {result.duplicates} duplicates</strong>{result.errors.map(e => <p key={e.row}>Row {e.row}: {e.error}</p>)}</div>}{error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Close</button><button className="primary">Validate & import</button></footer></form></Modal>;
}
export function FieldEditor({ close, saved }: { close: () => void; saved: () => Promise<void> }) {
  const [name, setName] = useState(''); const [type, setType] = useState<FieldDefinition['type']>('text'); const [options, setOptions] = useState(''); const [error, setError] = useState('');
  return <Modal title="Create a custom lead field" close={close}><form onSubmit={e => { e.preventDefault(); const id = 'cf_' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^\d+/, '').slice(0, 24) + '_' + Math.random().toString(36).slice(2, 6); void api('/api/workspace/fields', 'POST', { id, name, type, options: type === 'select' ? options.split(',').map(v => v.trim()).filter(Boolean) : [] }).then(saved).then(close).catch(e => setError((e as Error).message)); }}><label>Field name<input required maxLength={60} value={name} onChange={e => setName(e.target.value)}/></label><label>Value type<select value={type} onChange={e => setType(e.target.value as FieldDefinition['type'])}>{['text','number','boolean','date','select'].map(t => <option key={t} value={t}>{label(t)}</option>)}</select></label>{type === 'select' && <label>Allowed values, separated by commas<input required value={options} onChange={e => setOptions(e.target.value)}/></label>}<p className="notice">Creating a field does not supply its value. Every lead starts with Unknown. These fields cannot replace identity, permission, suppression, or calling policy.</p>{error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Create field</button></footer></form></Modal>;
}
export function RubricEditor({ rubric, close, saved }: { rubric: Rubric; close: () => void; saved: () => Promise<void> }) {
  const [value, setValue] = useState(structuredClone(rubric)); const [error, setError] = useState('');
  return <Modal title="Sales assessment rubric" close={close}><form onSubmit={e => { e.preventDefault(); void api('/api/workspace/rubric', 'PUT', { expected_version: rubric.version, approved: value.approved, criteria: value.criteria, description: value.description }).then(saved).then(close).catch(e => setError((e as Error).message)); }}><p>Version {rubric.version}. Models extract claims; the server computes categories. These are evidence points, not probabilities of winning.</p><div className="form-grid">{Object.entries(value.criteria).map(([name, weight]) => <label key={name}>{label(name)} weight<input type="number" min={1} max={5} value={weight} onChange={e => setValue({ ...value, criteria: { ...value.criteria, [name]: Number(e.target.value) } })}/></label>)}</div><label>Approved sales criteria<textarea rows={5} minLength={20} maxLength={2000} value={value.description} onChange={e => setValue({ ...value, description: e.target.value })}/></label><div className="rubric-rules"><p><strong>Unassessed:</strong> no approved rubric, no usable real calls, or fewer than two known criteria.</p><p><strong>Limited:</strong> explicit evidence of poor fit. <strong>Developing:</strong> evidence exists, but need and fit are not both confirmed.</p><p><strong>Promising:</strong> need and fit supported. <strong>Strong:</strong> need, fit, intent and authority all supported.</p><p>Conflicting answers stay unknown unless a confirmed human correction resolves them. Product facts still require the approved playbook.</p></div><label className="check-label"><input type="checkbox" checked={value.approved} onChange={e => setValue({ ...value, approved: e.target.checked })}/>I approve this rubric for commercial assessment</label>{error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save new rubric version</button></footer></form></Modal>;
}
